insert into setores values
(default,'Gerência de Atendimento Regional','2'),
(default,'Gerência de Monitoramento Eletrônico','2'),
(default,'Gerência de Implantação de Sinalização','2'),
(default,'Gerência de Elaboração de Projetos Viários','2'),
(default,'Gerência de Operações de Trânsito','3'),
(default,'Gerência de Educação Para a Mobilidade','3'),
(default,'Gerência de Estudos e Planejamento de Transportes','8'),
(default,'Gerência de Transporte Especial','8'),
(default,'Gerência do Sistema Integrado de Mobilidade SIM','8'),
(default,'Gerência de Gestão de Operações de Transprotes','8'),
(default,'Divisão ade Fiscalização de Transprotes','8'),
(default,'Gerência de Recursos Humanos','1'),
(default,'Divisão de Administração de Pessoal','2'),
(default,'Divisão de Recursos Humanos','1'),
(default,'Gerência Administrativa','1'),
(default,'Divisão de Patrimônio e almoxarifado','1'),
(default,'Divisão de Serviços Gerais','1'),
(default,'Divisão de Manutenção Predial','1'),
(default,'Gerência de Licitações e Contratos','1'),
(default,'Divisão de Licitações e Aquisições','1'),
(default,'Divisão de Contratos e Convênios','1'),
(default,'Gerência Orçamentária e Financeira','1'),
(default,'Divisão de Apoio Financeiro','1'),
(default,'Gerência de Planejamento para Mobilidade','6'),
(default,'Gerência de Tecnologia da Informação','6'),
(default,'Divisão de Infraestrutura','1'),
(default,'Gerência de Licenciamento de Projetos','6'),
(default,'Gerência de Análise e Processamento de Infrações','6'),
(default,'Divisão de Apoio a Junta Administrativa de Recursos de Infrações','6'),
(default,'Divisão de Atendimento e Relacionamento com Usuários','6'),
(default,'Divisão de Processamento de Infrações','6');